### ISSUE TITLE
If you have a div larger than the canvas, you cannot scroll to the bottom

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#1]
1) Create a box on the canvas.
2) Create a second box on the canvas below the first one.
3) In the properties panel, set the second box to have a height of 450 px.
4) Resize the first box with the south handle down to increase its height. Notice, it will push the second box around.
5) Try to scroll to the bottom of your application.

You cannot scroll to the very bottom.

**Comment by jtlafferty** [comment]
reported on the prerelease forum

I reproduced the issue and posted a bug file for internal use here:
https://www.dropbox.com/s/79nw9yl266ysgmx/Issue1.zip

**Comment by jtlafferty** [comment]
Heavenspot also reported this issue.

**Comment by jtlafferty** [comment]
This is a story in our sprint backlog and we have moved it into the next sprint.

**Comment by chrisbank** [comment]
I actually think this is fixed. There was an issue where you just couldn't get to the lower 45px of you page. That is fixed. There is a future user story to addd more virtual space to the bottom of the page so you can scroll even further than the bottom, but I don't think this is related.
