### ISSUE TITLE
Add eyedrop tool to color picker

### ISSUE THREAD

**Issue by line49** [edge-reflow/issues#102]
Feature Req: add colour picker to colour dialogs.

**Comment by jtlafferty** [comment]
We have a color picker for styles where a color is to be specified like background color, shadow color etc. It looks like this:

![screen shot 2013-10-02 at 10 00 14 am](https://f.cloud.github.com/assets/1831602/1255386/3ad7b2a6-2b84-11e3-962a-29d4a7501279.jpg)

Is it missing functionality that you are wanting?

**Comment by jtlafferty** [comment]
Is it an eye dropper that you want?

**Comment by jtlafferty** [comment]
An eye dropper is in our backlog.

**Comment by line49** [comment]
Hi Joan,

Good guess. Yes, sorry, I meant an eyedrop tool, to go with that picker.

Sounds good.
Dave
