### ISSUE TITLE
Setting an element to fixed width and left and right margin = auto doesn't center the element.

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#110]
Feedback from customer:
When we set fix width and left and right margin to "auto" of an Element manually, it does not fit to center

**Comment by jtlafferty** [comment]
I have tried this with very simple steps in Reflow and I cannot reproduce the issue, so, there is no current action we can take on this bug. If someone has reproducible steps, please add them to this bug.  

Steps I tried:
1. Add a box.
2. Change the width to use pixels.
3. Change the margins to auto

Result:The box looks centerred.

**Comment by anirudhsasikumar** [comment]
I can reproduce this with those exact steps. The key thing is applying float:none. (That's what the advanced -> float -> center button does). In our latest builds, there is an explicit button for float:none.

**Comment by placegraphichere** [comment]
yup, what @anirudhsasikumar said. reproducible when you don't change float from the Reflow "default".

**Comment by chrisbank** [comment]
So it's more a case of if left and right are set to auto in the Panel, then just auto remove the float too

**Comment by jtlafferty** [comment]
Yes! I am so used to setting margin: auto, by clicking on the "center" button of the Advanced Layout panel, that I forgot that this button also sets float to none.

**Comment by CoreyDotCom** [comment]
But is it really an issue now that there is a float none in PI? I mean we have a "center" button already, why do we need to automatically remove float if they set margins to auto?

**Comment by jtlafferty** [comment]
No, I don't think this is really an issue now. It is just a discoverability thing. I've pinged @placegraphichere to add this to our list of getting started topics.

Closing bug.
