### ISSUE TITLE
Font information from code popover does not work

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#111]
1. Add a text element to the canvas
2. Change the font to an EWF font.
3. Change the size of the text.
4. Preview in Chrome.

Things look correct.
1. Look in the code popover and copy the css for that text element.
2. Replace this css in your output css.

The font information is incorrect.  The font shorthand is something like:

font: aclonica 1.9em;

I believe it needs to be  

font: 1.9em aclonica;

This came from in-app feedback:
Why is it, when I view CSS within the software is doesn't give code that works properly. Example: font: (all font properies) doesn't really work, why not display it properly like. font-size: font-family: etc.... You seem to do it when you preview the pages, but not in the code...?

**Comment by vmitnick** [comment]
Submitted a fix for this; order was wrong where we generate the font shorthand.

**Comment by jtlafferty** [comment]
This fix is checked in and should be in our next update of Reflow.
