### ISSUE TITLE
Clicking on a project file does not open it in Reflow [ intermittent ]

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#117]
from in-app feedback:
One bug that I have found is when clicking on directly on my project from Finder, the project doesn't open. I have to close, then try again. It is random...sometimes it works fine, other times it doesn't open the file.

**Comment by jtlafferty** [comment]
This has been something we have seen internally for some time, but, it is intermittent.

**Comment by anirudhsasikumar** [comment]
This has been fixed in develop (and fix will be present in upcoming release).
