### ISSUE TITLE
Pressing Delete inside a Text box deletes the box rather than the text

### ISSUE THREAD

**Issue by foundationphp** [edge-reflow/issues#12]
Currently, the only way to delete the placeholder text in a Text box is by using the Backspace key. If you select the text and use the Delete key (to forward delete the text), the Text box is deleted instead of the text. This is incredibly frustrating.

Also, selecting Edit > Undo doesn't preserve any of the replaced text. Reflow simply creates a new Text box with the default placeholder text.

**Comment by JeffryBooher** [comment]
Hi David, this issue is fixed and you will be able to use the delete key with text  in the next build.

**Comment by foundationphp** [comment]
Woohoo! Great. Thanks, Jeff.

**Comment by jtlafferty** [comment]
Closing bug.
