### ISSUE TITLE
Can't paste an image

### ISSUE THREAD

**Issue by chriscalo** [edge-reflow/issues#126]
It's important to be able to screenshot or copy images to the clipboard and then paste them into Edge Reflow. This currently doesn't work.

**Comment by Shalaco** [comment]
Can I have an Amen!

**Comment by placegraphichere** [comment]
we're currently working on regular copy/paste for Reflow objects. We also support SVG copy/paste from Illustrator. This would be a great addition to those. I'm adding it to our backlog.
