### ISSUE TITLE
Show object edges should be off by default

### ISSUE THREAD

**Issue by chriscalo** [edge-reflow/issues#128]
I need to be able to see elements without this blue outline, but it won't go away.

![image](https://f.cloud.github.com/assets/867717/2058892/7c2555ee-8b8b-11e3-86ec-1d71ee24b5e9.png)

**Comment by chriscalo** [comment]
I found it. Show Object Edges.

In my humble opinion this should be off by default.

**Comment by CoreyDotCom** [comment]
Pretty standard default though no? e.g. Adobe InDesign.

**Comment by chriscalo** [comment]
It appears InDesgin does. Illustrator doesn't. Fireworks doesn't.

I don't really care either way now that I know how to turn it off. I just think when you're crafting something visual, you should be seeing exactly how it will appear.

**Comment by nhalbakk** [comment]
Glad you found the setting.  Going to close this issue for now.  We'll err towards not changing the default given that's what Reflow users have gotten used to.
