### ISSUE TITLE
Link Percentage Width Abnormality

### ISSUE THREAD

**Issue by dallashall** [edge-reflow/issues#129]
I have 3 boxes with images as backgrounds, contained inside a parent container. Max width for the parent box is 1050px, max width for child boxes: 350px. Width for child boxes is 33.33%. Child boxes have a 1px border and an inset shadow. Without adding links to these boxes, everything displays normally.
![without links](https://f.cloud.github.com/assets/6579519/2073112/3cc57a84-8d50-11e3-96fc-e216ad056b22.png)

When a link is added to each box, the size is altered, and the last box gets pushed to the next line.
![with links](https://f.cloud.github.com/assets/6579519/2073117/7d60c058-8d50-11e3-80a4-4544e2241091.png)

This can be replicated without images as backgrounds in the boxes.

Changing the 1px border to 0px fixes the problem.

Increasing the border does not help.

Removing shadow has no effect.

**Comment by anirudhsasikumar** [comment]
Thank you for taking the time to report this.

I can confirm that this is a bug at Reflow's end and occurs when previewing in Chrome. We'll be fixing this shortly.

For the time being, there's no easy workaround, the only thing I can suggest is to edit boilerplate.css in `C:\Program Files (x86)\Adobe\Adobe Edge Reflow CC Preview\www\reflow\src\modules\htmlpreview\templates` and 
1. Add this CSS rule:

``` css
a {
    box-sizing: border-box;
}
```
1. Save the CSS file.
2. Restart Reflow.
3. Make a change to your design and preview in chrome again.

P.S: Cute pictures!

**Comment by jtlafferty** [comment]
This will be fixed in the next update of Reflow.
