### ISSUE TITLE
Line Height should accept a numeric value without a unit of measurement

### ISSUE THREAD

**Issue by foundationphp** [edge-reflow/issues#13]
The Line Height field won't accept a number without em, px, or %. Using a number without a unit of measurement is not only valid for the line-height property, it's the preferred way of specifying it. See http://meyerweb.com/eric/thoughts/2006/02/08/unitless-line-heights/.

**Comment by jtlafferty** [comment]
We are working on a fix for this.

**Comment by jtlafferty** [comment]
This should be fixed now.

**Comment by jtlafferty** [comment]
Re-opening, this isn't fixed yet.

**Comment by JeffryBooher** [comment]
This issue is now fixed.
