### ISSUE TITLE
Div Width

### ISSUE THREAD

**Issue by Shalaco** [edge-reflow/issues#131]
It's important to know the pixel width or percentage width of a div when creating it in addition to the distance from the side of page, top of page, and between other elements.

![screen shot 2014-02-21 at 10 20 54 pm](https://f.cloud.github.com/assets/2678912/2237112/80551998-9b89-11e3-8b15-69bb89d61e02.png)

**Comment by placegraphichere** [comment]
this is interesting, do you want it all the time? Or when the div is first created?

Thanks for logging all these issues! We appreciate it. 

For workflow issues, how-to and the like, check out the forum too: http://forums.adobe.com/community/edge_reflow_preview

**Comment by Shalaco** [comment]
Specifically I was referring to when you create a div. Its percentage from its nearest elements is currently shown. But what you really want to know when creating a div is its width in px and percents.   More than happy to poke and break your software and share feature requests. Glad you are finding them useful.  -S    

---Sent from a miniature keyboard made from glass.

On February 22, 2014, 12:13:30 PST, Seth Walker  wrote:this is interesting, do you want it all the time? Or when the div is first created?  Thanks for logging all these issues! We appreciate it.   For workflow issues, how-to and the like, check out the forum too: http://forums.adobe.com/community/edge_reflow_preview  —Reply to this email directly or view it on GitHub.

**Comment by vmitnick** [comment]
Thanks for the suggestion, we've noted the feature request. We'll let you if/when we implement it.
