### ISSUE TITLE
Can't see grid with background image

### ISSUE THREAD

**Issue by Shalaco** [edge-reflow/issues#132]
Once you apply a background image(pretty much the first thing I would do if I was using one) you cannot see the grid. 

You should be able to toggle the grid on and off, and it should lay on top of all elements when visible.

**Comment by placegraphichere** [comment]
you should be able to have both of these things. I am able to see the grid when applying a background image.
![screen shot 2014-02-22 at 2 06 33 pm](https://f.cloud.github.com/assets/3229167/2238700/1c18543a-9bfd-11e3-85b1-2d3b3fc0433b.png)

The grid can also be toggled.
![screen shot 2014-02-22 at 2 06 56 pm](https://f.cloud.github.com/assets/3229167/2238705/26c3c0cc-9bfd-11e3-93b3-fb01d27d7615.png)

**Comment by Shalaco** [comment]
See screenshot.Unable to see grid after applying background image.     

---Sent from a miniature keyboard made from glass.

On February 22, 2014, 12:09:08 PST, Seth Walker  wrote:you should be able to have both of these things. I am able to see the grid when applying a background image.  The grid can also be toggled.  —Reply to this email directly or view it on GitHub.

**Comment by CoreyDotCom** [comment]
Shalaco, I seem to be missing your screenshot? Where is it?

**Comment by Shalaco** [comment]
Can you see this?

[image: Inline image 2]

~Shalaco

T 415.787.3083

E Shalaco@gmail.com

http://www.shalaco.com/gerund/
Let's be friends on the internet: [image:
Facebook]http://www.facebook.com/profile.php?id=shalzers [image:
Flickr] http://www.flickr.com/photos/shalaco [image:
Twitter]http://www.twitter.com/shalaco

**Comment by CoreyDotCom** [comment]
Nope.

**Comment by placegraphichere** [comment]
maybe try an external image service and just post a link to it here @Shalaco

**Comment by Shalaco** [comment]
https://www.evernote.com/shard/s9/sh/e4ef9534-cf37-4e5e-a8dd-52d88eacfef4/c647411fd229b53516ce6d9615541ede

~Shalaco

T 415.787.3083

E Shalaco@gmail.com

http://www.shalaco.com/gerund/
Let's be friends on the internet: [image:
Facebook]http://www.facebook.com/profile.php?id=shalzers [image:
Flickr] http://www.flickr.com/photos/shalaco [image:
Twitter]http://www.twitter.com/shalaco

**Comment by placegraphichere** [comment]
Cool thanks, I think most likely the grid is simply getting lost in the details of your image. Perhaps try a different image to confirm that?

I think we have to consider this an edge case of the grid display. Perhaps in the future we can consider ways to lighten and darken the grid. Or better ways to overlay the grid to avoid the loss if detail when an image like that is used. 

Thanks for following up!

**Comment by Shalaco** [comment]
My pleasure. Love helping out.
I'm right down the street from Adobe HQ, so I'm probably a stones throw
from you right now.

Revise bug: Grid gets lost in obscure, light images with strong vertical
lines.
Use case: obscura.
Mark: resolved.

https://www.evernote.com/shard/s9/sh/7dc84793-4cbc-4eae-a4ff-c198aa1f8c03/9e7da1251d62b48b0d1172d2d0c571bc

~Shalaco

T 415.787.3083

E Shalaco@gmail.com

http://www.shalaco.com/gerund/
Let's be friends on the internet: [image:
Facebook]http://www.facebook.com/profile.php?id=shalzers [image:
Flickr] http://www.flickr.com/photos/shalaco [image:
Twitter]http://www.twitter.com/shalaco

**Comment by vmitnick** [comment]
This is resolved, as not really a bug.
