### ISSUE TITLE
CSS Styling is lost when project opened from Finder

### ISSUE THREAD

**Issue by anirudhsasikumar** [edge-reflow/issues#133]
Reported on http://forums.adobe.com/message/6152978

Steps:
1. Double click RFLW file in finder.

Actual: Intermittently, canvas is blank. Regions load, pages load. Save wipes out CSS.
Result: Canvas display elements in file.

Fix is in progress

**Comment by anirudhsasikumar** [comment]
Workaround: Use File -> Open or Drag and drop file to app instead of double clicking RFLW files in finder.

**Comment by chrisbank** [comment]
fixed, will be out in next public release
