### ISSUE TITLE
Add ability to use cursor keys in numeric inputs

### ISSUE THREAD

**Issue by mstade** [edge-reflow/issues#16]
Many inputs are single numeric inputs and could benefit from recognizing the pressing of the  `up` and `down` keys, for nudging numbers.

**Comment by jtlafferty** [comment]
Yep, we have this on our backlog of enhancements to do. We'll update this bug when we are working on it or have it done.

**Comment by jtlafferty** [comment]
This is slated for next sprint.

**Comment by jtlafferty** [comment]
This should be available in the next prerelease drop of Reflow.
