### ISSUE TITLE
Optionally hide layout and styling tabs

### ISSUE THREAD

**Issue by mstade** [edge-reflow/issues#17]
Currently, the work area where breakpoints are defined share the horizontal space with the layout and styling tabs. It'd be very nice to be able to hide these when testing a layout, giving the working area the full width. It's especially useful when using multiple monitors with different orientations.

**Comment by jtlafferty** [comment]
There is a story in our backlog for this.

**Comment by jtlafferty** [comment]
This will be available in the next drop to the prerelease in the coming days.
