### ISSUE TITLE
CANT IMPORT ANOTHER PROJECT, WHILE ONE IS OPEN

### ISSUE THREAD

**Issue by ttodua** [edge-reflow/issues#176]
For example, i opened one ReFlow project (file), and want to copy parts from another reflow project(file) - i cant opent the second one! it asks me to close the first one... how to import parts from another file?

**Comment by vmitnick** [comment]
This is correct; a limitation of Reflow is that you can only open one project at a time, so there is no direct way to copy from one project to another.

You can create an additional page in your Reflow project and copy things between the pages, which may work for you depending on how much work you already have in each project.

For some workflows, you can also create a "template" project that you copy and use as a starting point for each project, but that doesn't sound like it will help you at this point.
- Vic
