### ISSUE TITLE
You can get into a state where the background color of a box won't change

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#18]
(reported by Heavenspot)

1) Open this project: https://www.dropbox.com/s/5q2crpe3swwxuh5/Issue18.zip
2) While in the default region, select the box in the center and try to change its background-color.

Actual: The color looks like its updated in the properties panel, but, the box on the canvas isn't reflecting the color.

**Comment by jtlafferty** [comment]
A developer on our team looked at this bug and believes it is due to some problems we need to fix around saving the project. It looks like the same media query is being written out multiple times to the json file. So, they are probably overriding each other.

**Comment by jtlafferty** [comment]
We should fix this in this sprint.

**Comment by anirudhsasikumar** [comment]
Looking into this.

**Comment by anirudhsasikumar** [comment]
A potential fix for this has been checked in. The attached project will still repro the issue since it has stale media query entries in it, shouldn't happen when building from start.

Leaving this open till people play around with it more and confirm the issue has been fixed.

**Comment by jtlafferty** [comment]
Closing this bug. IF someone sees the issue again, we will reopen it.
