### ISSUE TITLE
When you open a saved reflow file, the grid opacity does not reflect the right value

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#19]
1) Start a reflow project
2) Set the grid opacity to 0.
3) Save the project and close Reflow.
4) Re-open Reflow and the saved project. Select the main content area. 

Result: In the grid options, you will see that Opacity is set to 1. However, for this saved project, the grid opacity is actually 0. It looks right on the canvas, but, the property panel is not updated correctly.

(reported by Heavenspot)

**Comment by jtlafferty** [comment]
I can still reproduce this bug with any reflow project saved with grid opacity changed.

**Comment by JeffryBooher** [comment]
Opacity is being saved and reloaded correctly for me but the slider in the PI is wrong

**Comment by jtlafferty** [comment]
@JeffryBooher That is exactly what I see.

**Comment by JeffryBooher** [comment]
This isn't just isolated to opacity. Reflow doesn't save gutter sizes, column count, etc... but reloading works because Reflow writes the styles behind the grid to the reflow project file.

**Comment by JeffryBooher** [comment]
The fix for this got pulled into master today and will be in the next drop.
