### ISSUE TITLE
When you double click on a rflw file to open it in Reflow, it doesn't always load the first time

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#21]
(reported by Heavenspot)
1. Double-click a reflow project file (when Reflow is closed)

Actual Result: Reflow opens, but, with a blank project. The second time you try to open the project, it will likely open correctly.

This bug is intermittent, but, I am able to reproduce it, sometimes.

**Comment by JeffryBooher** [comment]
is this Mac or Windows?

**Comment by jtlafferty** [comment]
I can repro on Mac. I tried a few times on Win and didn't see it happen, but, that does not mean it does not exist.

**Comment by jtlafferty** [comment]
We have not seen this bug happen in a while, so, I am going to close this bug. If it reappears, we will reopen the bug.
