### ISSUE TITLE
Right Click > Refresh resets the Canvas to a Blank state

### ISSUE THREAD

**Issue by darrellh** [edge-reflow/issues#27]
If the end user is working on a layout project, and decides to use this option (Right Click anywhere > Refresh) Edge Reflow defaults back to an empty project.

If there was no Fie > Save on the project, then its lost and the end user has to start over.

Problem: Refresh should not be refreshing to an empty project.

Darrell

**Comment by CoreyDotCom** [comment]
Thanks Darrell. This is actually a debug only option that will soon be stripped from the context menu.  It's functionally the equivalent of File->New, but we need to actually introduce said File->New before nixing the refresh.  Will leave this bug open to track until we do so.  Apologies for the lost work.

**Comment by darrellh** [comment]
Thanks Corey

Darrell

**Comment by jtlafferty** [comment]
High priority, we need to fix this.

**Comment by jtlafferty** [comment]
This should be fixed in our next drop.
