### ISSUE TITLE
When you rollover the body element in the DOMBar, there is no visualization that the body can be selected

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#28]
1) Add an element to your canvas.
2) Hover over the items in the DOMBar that look something like this:

body > container > selection <>

Hovering over the selection or the container puts a very bold highlight on the item you are hovering over. Hovering over the body does not give any indication that the body can be selected. This is confusing.

Some confusion around this was reported in the forum.

**Comment by chrisbank** [comment]
Fixed in next released build
