### ISSUE TITLE
Special characters in HTML

### ISSUE THREAD

**Issue by anirudhsasikumar** [edge-reflow/issues#30]
1. Open the sample pluralist project.
2. File -> Create Preview.

Expected: Text renders as in canvas.
Actual: Special ' or " characters have been UTF-8 encoded.

**Comment by michaelchaize** [comment]
And it's even worst if you had french accents :) Try with é, à, or è. Adding a <meta charset="UTF-8" /> would fix the HTML preview.

**Comment by jtlafferty** [comment]
This will be fixed in our next build drop.
