### ISSUE TITLE
Gradient popup vs Image popup getting messy

### ISSUE THREAD

**Issue by michaelchaize** [edge-reflow/issues#31]
It's a UI bug hard to explain, but I've found a way to reproduce it. It seems that if you say on a DIV 'I want to define a background image', and then finally decide that it's not necessary, then you just close the popup.

Then when you try to define a gradient on a DIV, the "Background image" popup is still in memory, and there is no way to remove it. It smells like a requireJS module that is not killed.

I'm attaching a PDF with screenshots to explain how to reproduce this bug. It happened to me several times designing a page... Oh crap. I cannot attach a PDF. Here is a link to my PDF (I don't want to attach images as I put comments on pages):

http://riagora.com/pvt_content/reflow/Reflow%20-%20bug%20-%20specify%20image-gradient.pdf

**Comment by michaelchaize** [comment]
If you cannot see the comments in the PDF:
Page 1: Create a DIV
Page 2: Set a gradient
Page 3: Click on the icon "Specify Background image". The popup is displayed. Close it.
Page 4: Create another DIV
Page 5: Click on "set a gradient". The "Specify an image" popup is displayed. 
You're stuck.

**Comment by jtlafferty** [comment]
Can you reproduce this every time? I feel like we have seen this issue, but, I just can't reproduce it. I've followed your steps.

**Comment by anirudhsasikumar** [comment]
I think Corey fixed this one.

**Comment by jtlafferty** [comment]
Great! I will close it. Michael, if you continue to see this in a build, please comment here and we will reopen the bug.
