### ISSUE TITLE
Can't make work the ^Drag (Objects are moved without reordering the DOM)

### ISSUE THREAD

**Issue by michaelchaize** [edge-reflow/issues#32]
When I look at the help section (keyboard shortcuts), it says that I can use ^Drag. 

I guess that by "^" we mean "ctrl". The shortcut to show/hide edges works fine (cmd + ctrl + H).

But I can't make the ^Drag (ctrl + Drag) working. The alt+Drag (to duplicate an object) works though. 

I want to make sure that our shortcuts will work on weird keyboards such as mine (French keyboard "AZERTY").

**Comment by jtlafferty** [comment]
This is probably an issue with the french keyboard which we have not tackled yet. We have a story in our backlog to deal with this. Closing because it is already in our backlog.
