### ISSUE TITLE
If the primary container has a padding set, the resize handles of an image don't draw correctly.

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#34]
1) Add 10px of padding to the top of the primary container.
2) Add an image to your canvas.

The resize handles of the image are 10px down from the top of your image.

See: https://www.dropbox.com/s/zuiei1m7bgm60jl/Screen%20Shot%202013-01-30%20at%206.22.12%20AM.jpg

This was reported on the prerelease forum.

**Comment by jtlafferty** [comment]
We will fix this soon. High priority.

**Comment by chrisbank** [comment]
looking into
