### ISSUE TITLE
Ui : Fix "transferred pictures" shadow on a thin blue text in EgInspect window

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#37]
Rendering is quite vibrating, not so legible.

I suppose it has to do with topcoat (which isn't anymore on Github http://adobe.github.com/topcoat/ -> 404)

![Bug-EgRflw-InspectWindow-shadow missGrab](https://f.cloud.github.com/assets/2315207/155279/2833685a-7641-11e2-9dbd-dc8db5c83df3.png)

Edit : 
Found reference to topcoat again (9 days ago    repo: ’adobe/topcoat’ >> ’topcoat/topcoat’ [noformnocontent])and there's no shadow under the blue text on a light interface http://htmlpreview.github.com/?https://github.com/topcoat/topcoat/blob/master/test/topcoat-component-test.html

**Comment by aaronshekey** [comment]
Can you describe your steps getting there? We've intentionally disabled this feature for the first iteration of Edge Inspect integration.

**Comment by fr32c** [comment]
Well, this is reversed work : I needed screen shots, so since i didn't have them on the desktop version, i asked them from the devices, where you still have access to it in Inspect. They get added (as expected) to the folder, and you've got this feedback.

**Comment by jtlafferty** [comment]
Is this blue text that you see showing up in Reflow? If so, please tell us your steps to seeing it. This might be a bug in Edge Inspect that you are reporting. So, I would like to clarify.

**Comment by fr32c** [comment]
Ok, i got the steps (sorry for the delay)

So first open reflow
launch inspect
put it on
start an inspect on a device
on a device press capture

there you have the "screenshots (captures ?) transferred" text that appears.

This is where we get the shadowed blue text.

And it's a light bug, i'd say "inconvenience", especially since, later, reflow will be able to request screenshots directly from the device.

included screenshots.

Franck

**Comment by jtlafferty** [comment]
We actually removed this text from the Inspect dialog. So, this bug no longer applies.
