### ISSUE TITLE
Add HTML Form elements

### ISSUE THREAD

**Issue by nhalbakk** [edge-reflow/issues#40]
On behalf of Christopher A Hunt on the Reflow forums:
http://forums.adobe.com/thread/1154596?tstart=0

Is there a plan to add HTML forms within Reflow?

**Comment by mayuco** [comment]
:pray:

**Comment by jtlafferty** [comment]
This is in our current roadmap.

**Comment by vmitnick** [comment]
Closing, since we have html form elements, as of Reflow Preview 7.
