### ISSUE TITLE
User expects escape key to dismiss popovers

### ISSUE THREAD

**Issue by vmitnick** [edge-reflow/issues#43]
Prerelease user Daniel Glazman said:
"when a popup is shown (shadow, background color, etc.), hitting the Escape key should close it w/o action."

https://prerelease.adobe.com/project/forum/thread.html?cap=FF6B725AE94F4BC085887924919A50DD&forid={D17ECF3F-4555-4693-BE0F-D5B53E9414BA}&topid={9DF963BC-9C74-4CA2-AF38-A9516B94CEB1}

**Comment by chrisbank** [comment]
fixed in next release
