### ISSUE TITLE
hard to see scrollbar in properties panel

### ISSUE THREAD

**Issue by vmitnick** [edge-reflow/issues#45]
Prerelease user Daniel Glazman said:

"if the viewport is smaller (in height) than the Styles tab, there is a scrollbar but that scrollbar is almost invisible."

https://prerelease.adobe.com/project/forum/thread.html?cap=FF6B725AE94F4BC085887924919A50DD&forid={D17ECF3F-4555-4693-BE0F-D5B53E9414BA}&topid={9DF963BC-9C74-4CA2-AF38-A9516B94CEB1}

**Comment by jtlafferty** [comment]
In our next drop of Reflow, we have made a change to our scrollbars that should help with this.
