### ISSUE TITLE
Should not show "apply to all" button if no other regions

### ISSUE THREAD

**Issue by vmitnick** [edge-reflow/issues#47]
style and grid controls show a button to apply the changes to all
    "regions". Even if there is no Media Query defined...

From prerelease user Daniel Glazman
https://prerelease.adobe.com/project/forum/thread.html?cap=FF6B725AE94F4BC085887924919A50DD&forid={D17ECF3F-4555-4693-BE0F-D5B53E9414BA}&topid={9DF963BC-9C74-4CA2-AF38-A9516B94CEB1}&tl=15&to=desc&tp=1

**Comment by nhalbakk** [comment]
Good point, can be confusing and detract from understanding the purpose of the apply to all regions button.

**Comment by chrisbank** [comment]
Fixed in the next released build
