### ISSUE TITLE
Press cmd (ctrl on a PC) while using any tool to temp switch to selection tool.

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#49]
If you are not familiar with Ai (or even Ps) :

When you are in "create box mode", which is, with the box tool (M). Sometimes you want to move your box just after creating, before creating the next one.

Actually, it means :
1. pick box tool (M)
2. trace box
3. pick select tool (V)
4. adjust box place (or anything else)
5. pick box tool (M)
6. trace next box
…

It requires you to switch between M, V, T, which even on a qwerty keyboard aren't nicely set together.

I'd love a "modifier keydown/keyup"  (cmd/ctrl) to get the select tool.
1. pick box tool (M)
2. trace box
3. temporarily pick select tool (press cmd)
4. adjust box place (or anything else)
5. go back to box tool (release cmd)
6. trace next box
   …

It allows me to stay in the flow of creating boxes (M tool), keep the left hand on the bottom left of the keyboard to use the shortcuts (cmd, alt, shift…), edit, modify, etc.

When i want to go from box tool to type tool (T), i know i want to change, it's a special brain movement to go to (T), same if i know i'm only selecting and editing, going to (V).

**Comment by jtlafferty** [comment]
This should be in our latest public update of Reflow. If you are in box or text insertion mode, you can click Cmd/Cntl to temporarily go into selection mode.
