### ISSUE TITLE
Spacebar while tracing text box to move origin of object

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#50]
in inDesign, Photoshop, Illustrator, if you're tracing anything, selecting, etc, while doing (not releasing the mouse), if you press the space bar, then that object moves with the mouse, until you release the spacebar, and you can keep on resizing it : 
If you start drawing a box from second column and realize it should be put on the next column, you press the space bar, move origin, release the spacebar and size it the way you want.

**Comment by jtlafferty** [comment]
Great suggestion. Marked as High priority, we'd like to get this in. We'll update you when its in.

**Comment by jtlafferty** [comment]
This is in our latest public preview.
