### ISSUE TITLE
Resizing Image bug. 

### ISSUE THREAD

**Issue by Areshov** [edge-reflow/issues#51]
Resizing image from the left bottom cause to move image to top.

This doesn’t happened when we are resizing from another corners of image.

**Comment by CoreyDotCom** [comment]
Thank you for reporting.
This issue was previously reported and is being tracked internally as #1051.

**Comment by nhalbakk** [comment]
This is high priority and hoping to resolve it in our next update.

**Comment by chrisbank** [comment]
Fixed in the next released build
