### ISSUE TITLE
Export option - Idea

### ISSUE THREAD

**Issue by igfxstudios** [edge-reflow/issues#52]
Hi everyone,

This not an issue but rather an idea that I would to share with the team.

Export option:
http://www.igfxstudios.com/AdobeReflow/export/detail_Reflow_Export.pdf

I would love to get your views: fmark@igfxstudios.com

Francois

**Comment by CoreyDotCom** [comment]
Hi Francois, I see you posted in the Ideas forum which is the perfect place for something like this. Much appreciated. Going to close this down and reserve this repository for bugs/issues.  

E.g. : http://forums.adobe.com/community/edge_reflow_preview?view=idea
