### ISSUE TITLE
Resize image not working after query change

### ISSUE THREAD

**Issue by AndreasGalster** [edge-reflow/issues#53]
Unforunately I am not 100% sure how to reproduce the error. I had an image in a box (div), which wasn't set too 100% width in a media query. Then I switched two media queries below and wanted to give the image 100% width. Setting it to 100% didn't rescale the width to 100% though. Nothing happened to the image. It was like the image didn't have any relation to anything. Setting the width for a text box in the same div to 100% did work however.

I tried setting the image width above 100% (150%), which worked correct and after that the image got the 100% width right.

**Comment by jtlafferty** [comment]
Do you happen to have the project that showcases this bug? If you post it somewhere, I'll grab it. That would be helpful.

**Comment by AndreasGalster** [comment]
Yes, I do. However, the bug has been "fixed" by me already as I described it above. But if it is still helpful, here are the project files. I switched from the 1024 break point to the 662 break point - that's where the 100% didn't work initially.

http://andreasgalster.com/online_portfolio_blog.rar

**Comment by jtlafferty** [comment]
Thanks, we'll have a look!

**Comment by jtlafferty** [comment]
looking into this today. This should be a part of our M4 milestone if it can be reproduced.

**Comment by jtlafferty** [comment]
I wasn't able to reproduce this issue, so, we are going to close this for now. If reproducible steps are found in the future, we'll reopen. Hopefully, the issue has been resolved, we have done a lot to layout in the next drop of Reflow.
