### ISSUE TITLE
Match height/width should match the height/width of the first selected or last selected one.

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#55]
Reported on forum post:
http://forums.adobe.com/message/5145305#5145305

"Match height/width always takes the biggest width. It should take either the first selected one's, the last selected one's, or an active one like in Illustrator."

**Comment by fr32c** [comment]
I fell on that one too. See Illustrator or inDesign's "align on key object"'s behaviour: select items (drag, shift click…), click once more (no key pressed) to have a thicker selection mark on one item, then apply whatever align/make same height etc.

**Comment by jacobsurber** [comment]
We have modeled out behavior after Fireworks, matching height to the largest selected item.  I'm going to close this as an enhancement that we are not currently planning on implementing, but let's talk about it again in the future.

Thanks for your idea though!

**Comment by fr32c** [comment]
Jacob, i'm quite new to github, but how do i track that "enhancement" for later, how am I sure that this might someday get out of the box again, and not have to ask again ?
