### ISSUE TITLE
If a user cancels out of the image dialog, the Layout pane becomes blank

### ISSUE THREAD

**Issue by jtlafferty** [edge-reflow/issues#56]
1) In Reflow, select the image tool bringing up the file dialog.
2) In the dialog, click Cancel.

Result: Layout pane is blank. You need to click on the Canvas to get it back.

**Comment by jtlafferty** [comment]
Reported on the prerelease forum.

**Comment by jaredwy** [comment]
This has been closed now and should be addressed in the next release.
