### ISSUE TITLE
Failed to load

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#57]
First time i unzipped the dmg, dragged and dropped to the apps folder of my Mac, and launched it, i got this message "Reflow has failed to load", i quit and launched again with no problem, so it's not critical but is interesting to investigate (dr10)

**Comment by jtlafferty** [comment]
Thanks Franck, we'll make sure this doesn't happen on the public preview!

**Comment by jtlafferty** [comment]
This should be resolved with our last drop. Closing.
