### ISSUE TITLE
Tooltips translations

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#59]
In the french version of Reflow, if i hover some elements, i get a nice literal translation:

Effacer : Effacer à gauche, les deux, à droite
(for clear: clear:left, both, right)

Although it's semantically correct, problem is that it might raise issues on beginners not knowing exactly what it refers to.

Edge Animate's tooltips state: style="left:valuepx"

a bit surprising for french users at first, it becomes really handy when : debugging, looking for references, learning css and good practices.

**Comment by jtlafferty** [comment]
I sent this bug along to our translation team to investigate this. Thanks!

**Comment by fr32c** [comment]
You mean, i should also log here : https://translate.adobe.com/adobe/projects/753/translate/category/2?page=4 :)

**Comment by fr32c** [comment]
By the way, that makes it way longer in the french version, and i wonder if it shouldnt be interesting in english too for the strings instead of "Clear Right" to have (clear:right) or something like that…

**Comment by jtlafferty** [comment]
No need to log this anywhere else. We work closely with our translation team and I have sent them your feedback already. Thanks!

**Comment by ybayer** [comment]
Thanks for your feedback on French translation! 

I wanted to understand your suggestion clearly before contacting to our localization vendor. I'd really appreciate if you could attach a screenshot of Edge Animate" where you described:  
“Edge Animate's tooltips state: style="left:valuepx"

Also, could you confirm this is how you're suggesting to change current translations? Basically you're suggesting to not translate the tool tips literally where property values are being set. Is that correct?

For example,

ID: TOOLTIP_CLEAR_RIGHT
English:Clear Right
Current French: Effacer à droite
Suggestion: clear:right

English:Float Left
Current French: Flottement à droite
Suggestion: float:left

**Comment by fr32c** [comment]
This is a tool tip on animate:
![Capture d e cran 2013-03-25 a 20 16 52](https://f.cloud.github.com/assets/2315207/299642/95d67f88-9580-11e2-897c-1bfc78f7f765.png)

So what you propose sounds good to me, although, i went on the public translate.adobe.com website to propose that already (for the "clear" function)

What i'm wondering is what would be better:

this (what you propose) sounds like direct technical translation (as in Animate):

ID: TOOLTIP_CLEAR_RIGHT
English:Clear Right
Current French: Effacer à droite
Suggestion: clear:right

May be we could think about halfway (and sorry for the length:

ID: TOOLTIP_CLEAR_RIGHT
English:Clear Right
Current French: Effacer à droite
Suggestion: Effacer à droite (clear:right)

that would give both understandable translation (i hope french people approaching web have basis in english, but i still doubt it), AND useful comprehension of what code is being injected in the css.

What do you think about that ?

**Comment by ybayer** [comment]
Thank you for your recommendation. I will bring this up to the product team.

**Comment by fr32c** [comment]
Do you think i should raise the issue on the reflow forum and/or twitter to see if it's not just me that likes the "raw code underneath" ?

**Comment by jtlafferty** [comment]
Yoko, the product team believes that there should be no translation as @fr32c suggests where clear:right is just clear: right.

On the Reflow side, we should not have Clear Right, we will change this to use clear:right instead.

**Comment by jtlafferty** [comment]
Actually, in talking more to the team, the solution we like is @fr32c suggestion to go with something like:

English:Clear Right
Current French: Effacer à droite
Suggestion: Effacer à droite (clear:right)

**Comment by jtlafferty** [comment]
This should be fixed now and will be available in our next drop.
