### ISSUE TITLE
Rename from DOM panel: Tab to rename next

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#61]
I love the rename from dom panel, it's really practical and will make the generated code more usable.

I'd like a feature Photoshop introduced in CS5 or 6, which is : in its layer panel, when you rename some layer, if you press enter, it validates (historic behavior, same as what we've got in Reflow), but now, if you press tab, it selects the layer just under and goes to rename mode. 

This allows to quickly rename a lot of page elements.

**Comment by jacobsurber** [comment]
We've made a story for this in our backlog.

**Comment by jtlafferty** [comment]
A fix for this has been checked in and will be in our next update of Edge Reflow.
