### ISSUE TITLE
Hold Shift to snap breakpoints in increments of 10px

### ISSUE THREAD

**Issue by benoneal** [edge-reflow/issues#65]
It's a pain to have to first drag the breakpoint to approximately where you want it, then create a breakpoint, then open the breakpoint drop-down menu to type in what the px width should actually be.

**Comment by jacobsurber** [comment]
This is a good point.  I'm creating an investigation story in our backlog.

**Comment by CoreyDotCom** [comment]
Fixed locally.

**Comment by chrisbank** [comment]
Fixed merged. Will be in next public release.
