### ISSUE TITLE
Better typography management is essential

### ISSUE THREAD

**Issue by benoneal** [edge-reflow/issues#67]
Similar to other Adobe products, it would be a godsend to be able to create multiple predefined typography styles. For example: global typeface, global heading typeface, global font size, global font colour, and then to be able to specify individual overrides for headings and paragraphs, similar to how paragraph styles work in photoshop and indesign. 

Currently, individually adjusting every new text element is a huge repetitive waste of time.

**Comment by jacobsurber** [comment]
This is partially solved in our upcoming release.  You will be able to define default document styles.  After that we will begin working on a larger global style management story.

**Comment by jtlafferty** [comment]
The following will be available in the next drop of Reflow: global typeface, color, size, line height, style, weight and spacing. They are already checked into our build, so, I am closing this request.

The other suggestions here will be considered for the future as Jacob mentioned in the last comment.
