### ISSUE TITLE
Need tools shortcuts

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#7]
We need basic tools shortcuts for rectangle, text, and image frame.

Let's get inspired by existing tools :

inD : Rect (M) Text (T) Place (cmd-D+DragNDrop)
Ps : RectSelection (M) Text (T) Place (none or DragNDrop)
EgAn : Rect (M) Text (T) Place (cmd-I +DragNDrop)

(M and T seem obvious here, import is different)

**Comment by jtlafferty** [comment]
We have a sprint backlog story to do a shortcuts audit.

**Comment by jtlafferty** [comment]
This should be available in our next drop of Reflow. We have added M for Box, T for Text, I for Image and V for the selection tool.
