### ISSUE TITLE
Better Developer Workflow

### ISSUE THREAD

**Issue by jcampbell05** [edge-reflow/issues#71]
I think it would be nice if it worked more as a part of a workflow.

For example if it could integrate with other Grid Frameworks like Bootstrap or Zurb Foundation (Perhaps in the future add plugins for this.

It would be nice also if you could change the styling language from using CSS to SASS or SCSS or Even LESS. This would be especially awesome, it could perhaps use the local compiler to compile all generated SASS.

The main problem with Reflow for me is its an amazing tool for responsive web design and well overdue; I was considering making one if you guys hadn't but I don't want to be rewriting the code it exports just to use our preferred grid system (promotes consistency across our sites) or to rework it into SASS (Makes colour scheme changes easier).

**Comment by jacobsurber** [comment]
Hi jcampbell05, the current focus of Reflow is to be the best design tool possible, built on an HTML stack.  We have made a philosophical decision at this point to not focus on developer features, but to focus on the design workflow.  We want RF to be a tool for designers to be able to communicate their design intent.  All of that said, we are always evaluating workflow and user needs.  I'm going to close this bug, but we will revisit this idea in the future.

**Comment by jcampbell05** [comment]
I understand that its just it would be nice if, they could do mock ups and the style code is in scss. Which is nice for developers as we don't need to rewrite the code in scss and its nice for them as they don't need to bother knowing all the vendor prefixes etc :)
