### ISSUE TITLE
Style Manager and Web Fonts

### ISSUE THREAD

**Issue by jcampbell05** [edge-reflow/issues#72]
I think it would be nice to have a style manager for Headers etc. I think this would be useful as I quite often want all my headers etc to have a consistant style.

:) also I think it would be awesome to add support for Web Fonts :) (Perhaps allow a user to select a custom font installed on their computer and Reflow could convert it to the required formats)

**Comment by jtlafferty** [comment]
Thanks for the feedback, we've got a lot of work in style management still planned for future releases.

With regards to web fonts, our next drop will allow you to add a typekit kit to your project, but, not fonts on your computer. This has been asked for by others, so, it's in our backlog.
