### ISSUE TITLE
Images in the library preview should be shown at the optimal size

### ISSUE THREAD

**Issue by g1sh** [edge-reflow/issues#75]
It seems like the preview of the images in the library is always showing at a specific size. This makes it so small images get stretched and big images don't use the space in the right way.
![screen shot 2013-05-14 at 3 10 06 pm](https://f.cloud.github.com/assets/1661206/504670/d2cc7034-bcf2-11e2-97fc-5fe3a344af3f.png)
![screen shot 2013-05-14 at 3 08 26 pm](https://f.cloud.github.com/assets/1661206/504671/d2dab50e-bcf2-11e2-8acc-615e36c94ef1.png)

**Comment by jtlafferty** [comment]
This was fixed in our latest builds and will be available in the next release of Reflow.
