### ISSUE TITLE
Image resize - clip

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#8]
So far, i haven't found a way to have an image resize as a background-image property unless it's a rectangle + background image.

**Comment by jtlafferty** [comment]
Can you clarify what you are trying to accomplish? Are you trying to use the image tool and resize it? Or, are you talking about trying to scale background images?  The later functionality should be available already.  When you add a background image to a box, you can edit the scale property.

**Comment by jtlafferty** [comment]
Closing this issue for now because we need more information. Let us know if you have more info and want us to reopen this.
