### ISSUE TITLE
Scrubby Sliders [Feature Request]

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#80]
It has become recurrent in many Adobe apps (photoshop, flash, animate, etc), press and drag on numerical value (or on the icon next to it) should allow to manually change this value, within the limits possible in the field, with modifiers for steps (say i press shift or alt and i got units, or 10th…).

This is far from some requests from developers, this is closer to a designer's need.

**Comment by jacobsurber** [comment]
This is on our backlog and something that we will hopefully be tackling soon!

**Comment by jtlafferty** [comment]
This is feature will be available in our next update.
