### ISSUE TITLE
RGB color selector in gradient panel

### ISSUE THREAD

**Issue by newb7147** [edge-reflow/issues#81]
The gradient panel is automatically adding a ) after just 1 number in the last sequence when you type in a color.  You get 124,39,8)9.  I have replicated this 6 different times as I added new colors.  My version of reflow is up to date.

**Comment by CoreyDotCom** [comment]
What color are you typing in, can you provide step by step?

**Comment by CoreyDotCom** [comment]
I tried "rgb(124,39,89)" and it worked.

**Comment by newb7147** [comment]
Its doing that with any color I type in.  As I'm typing it (123,39,89).  It automatically closes it after the first number in the last sequence.  I am in the box div with text on top and putting a gradient in the background of the box.  There are 6 different colors on the gradient and I had this issue with every color.  I had to go into the parenthesis with my mouse or backspace the ) reflow added.     Other colors were (235,168,193), (199,50,85), (124,19,44), (148,23,52),(163,27,76), (186,29,86).

**Comment by CoreyDotCom** [comment]
Ah, are you skipping rgb though?  Right now Reflow doesn't understand (199, 50, 85) as it could be hsl, rgb, rgba, etc.  rgb(235, 168, 193) works?

**Comment by newb7147** [comment]
No, the rgb is there.  I just left it out of this post for brevity sake.  Sorry for the confusion.

**Comment by CoreyDotCom** [comment]
I still can't reproduce. Lastly, what version of Reflow are you using? Our QA will spend some time with it. Thanks for your help!

**Comment by newb7147** [comment]
0.12.9232

**Comment by jtlafferty** [comment]
We fixed this bug since our last public preview. I can definitely reproduce your bug in 0.19.9232 and I cannot reproduce it in our latest version which will be out to the public VERY soon.
