### ISSUE TITLE
Boxes resize and move on almost every click

### ISSUE THREAD

**Issue by stinnett-casey** [edge-reflow/issues#82]
When I click on a box that is next to another box, the box that I did not click on re sizes. So I have to click on the height and width input boxes and type in the height. I can't just drag the height because that will re size everything else! I think that each box should be independent of the other boxes except concerning margins and the like.

Also, when I am editing on one break point, lots of other boxes and images are moved around on the other breakpoints that I am not editing. I think that each break point should be independent of the others.

**Comment by CoreyDotCom** [comment]
Yes this is most certainly a regression that you are experiencing.  Will investigate and resolve soon (and post any additional data here as we find it).

**Comment by CoreyDotCom** [comment]
Can you possibly tell us what version you are using? Downloaded from Creative Cloud or Prerelease ?

**Comment by stinnett-casey** [comment]
I downloaded it from the Creative Cloud. It is the preview.

2013/6/21 Corey Lucier notifications@github.com

> Can you possibly tell us what version you are using? Downloaded from
> Creative Cloud or Prerelease ?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/edge-reflow/issues/issues/82#issuecomment-19848569
> .

## 

-Casey Stinnett
928-243-8696

**Comment by CoreyDotCom** [comment]
Thank you very much. If you can snag an exact version number that would be great, also, what platform are you running on (OSX or Windows)?

**Comment by stinnett-casey** [comment]
I will find the version number soon. I am running it on Windows 7
Enterprise.

2013/6/22 Corey Lucier notifications@github.com

> Thank you very much. If you can snag an exact version number that would be
> great, also, what platform are you running on (OSX or Windows)?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/edge-reflow/issues/issues/82#issuecomment-19855419
> .

## 

-Casey Stinnett
928-243-8696

**Comment by stinnett-casey** [comment]
This is the version that I am using: 0.23.10993 (preview)

2013/6/22 Casey Stinnett stinnett.casey@gmail.com

> I will find the version number soon. I am running it on Windows 7
> Enterprise.
> 
> 2013/6/22 Corey Lucier notifications@github.com
> 
> > Thank you very much. If you can snag an exact version number that would
> > be great, also, what platform are you running on (OSX or Windows)?
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/edge-reflow/issues/issues/82#issuecomment-19855419
> > .
> 
> ## 
> 
> -Casey Stinnett
> 928-243-8696

## 

-Casey Stinnett
928-243-8696

**Comment by jtlafferty** [comment]
Hi, we believe we have tracked the problem, but, wanted to verify with you a workaround.

If you change regions by double clicking a breakpoint (or the default breakpoint) before making any changes to elements on the canvas, do things work a lot better?

**Comment by stinnett-casey** [comment]
I double clicked on both the colored section representing the breakpoint
and on the knob that shows the end of the break point and neither changed
anything. The other breakpoint pages still got messed up after moving some
divs. Or boxes, as they're called.

2013/6/24 Joan Lafferty notifications@github.com

> Hi, we believe we have tracked the problem, but, wanted to verify with you
> a workaround.
> 
> If you change regions by double clicking a breakpoint (or the default
> breakpoint) before making any changes to elements on the canvas, do things
> work a lot better?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/edge-reflow/issues/issues/82#issuecomment-19940800
> .

## 

-Casey Stinnett
928-243-8696

**Comment by CoreyDotCom** [comment]
We appreciate your time helping out on this issue.  

Can you provide some specific repro steps and perhaps post a sample so we can follow your exact steps on your exact test case?

**Comment by stinnett-casey** [comment]
Here is what I have been working on. This is the one where if I adjust any
of the divs, then the divs in the other breakpoints also move.

2013/6/25 Corey Lucier notifications@github.com

> We appreciate your time helping out on this issue.
> 
> Can you provide some specific repro steps and perhaps post a sample so we
> can follow your exact steps on your exact test case?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/edge-reflow/issues/issues/82#issuecomment-19980326
> .

##

**Comment by jtlafferty** [comment]
stinnett-casey, I'm not sure if you tried to link to a project in your last comment, but, I don't see it. Please repost a comment with a link to the project you referred to our send me the project at tan at adobe.  Again, thanks for the bug. It seems like a terrible one, so, we want to get to the bottom of it.

**Comment by neilio** [comment]
I'm glad this is being looked into as it's driving me crazy. I have a two column layout and every time I change the size of a box in the right rail the main content box shrinks. Then when I try to fix the size of the main box the right rail boxes change. I've basically given up until this gets fixed as it makes the app unusable.

**Comment by agrayhound** [comment]
I have exactly this same issue, and I have given up too. Every time I change the size of one box it re-sizes some others.

Using: OSX: 10.8.4
Edge reflow: 0.23.10993

**Comment by jmclemore65** [comment]
Same here! I work for an agency trying to come up with a solution for responsive advertising and started with Reflow. Each breakpoint should work just like a media query. I'm going nuts adjusting something at 728 only have it to screw up my 320. Help please! :)

**Comment by jtlafferty** [comment]
We checked in a solution that will make it harder to move boxes as you a clicking around a design. @jmclemore65 , I don't think this will resolve your problem with things moving as you change breakpoints. This is a different problem and we are still thinking about how to resolve it.

The original bug should be fixed in the next update of Reflow.
