### ISSUE TITLE
Can't select multiple elements

### ISSUE THREAD

**Issue by stinnett-casey** [edge-reflow/issues#83]
I want to be able to select more than one element, whatever that element is, and then apply certain measurements to them at the same time (e.g., float: left;) but I can only select all elements under the square I can draw with the cursor.

**Comment by vmitnick** [comment]
You can also select multiple elements with shift-click (hold the shift key as you click on additional elements). That should provide what you want.

**Comment by jtlafferty** [comment]
You can also hold cmd/ctrl while dragging and selecting elements. This will select anything in your selection rectangle, but, not the parent of those elements. Hope that helps.

**Comment by stinnett-casey** [comment]
That did it! Thank you much!

2013/6/20 Joan Lafferty notifications@github.com

> You can also hold cmd/ctrl while dragging and selecting elements. This
> will select anything in your selection rectangle, but, not the parent of
> those elements. Hope that helps.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/edge-reflow/issues/issues/83#issuecomment-19765176
> .

## 

-Casey Stinnett
928-243-8696

**Comment by jtlafferty** [comment]
Great! I'm going to close this bug.
