### ISSUE TITLE
Blinking when resizing

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#85]
Built a small basic page, two frames next to each other. 
Testing in Chrome, when i resize, the elements keep on staying top, going left, top, left.
See this movie (.mov) for reference : http://fr32c.free.fr/Reflow/R25-blinking.mov
Don't know if it's expected, i join the zip file : http://fr32c.free.fr/Reflow/R25.zip

**Comment by jtlafferty** [comment]
Thanks, for the report. We have seen this issue already and are trying to figure out how to resolve it.

**Comment by jtlafferty** [comment]
We have made some refinements in our values are calculated and this issue should be much improved in the next update. You will still see the issue with older projects however. New projects should not see this issue.
