### ISSUE TITLE
Container Properties broke down

### ISSUE THREAD

**Issue by nhalbakk** [edge-reflow/issues#86]
Bug: Container properties broke down
Jul 11, 2013 7:24 AM
I hit this bug in one of my files- the container properties stopped working in this file, causing wierd things to happen. I couldn't set the width,  number of columns etc. I deleted everything in the doc to make sure it wasn't something else, but still didn't work.

Filed from: http://forums.adobe.com/thread/1252502?tstart=0

**Comment by jtlafferty** [comment]
I believe this is related to some issues where a document would get corrupt and you could not save or other actions. This should be fixed in the latest update.
