### ISSUE TITLE
Remove Parent not in the Undo stack

### ISSUE THREAD

**Issue by ponderWoods** [edge-reflow/issues#89]
Hey guys, really enjoying Reflow over here!

I ran into a frustrating issue though, It was mostly a case caused by random user clicking. However I was expecting cntl-Z to fix it for me.

I styled some text by highlighting it which created a span, I tried to use the Edit->Remove Parent feature to push the <span> back up to the <div> the text was in. And my whole header vanished on me.

**Comment by CoreyDotCom** [comment]
Good catch.  We did in fact remove the parent but in this case it was the parent text element and not it's container.  

Odd that undo didn't bring it back though. I can't seem to reproduce that part, but either way it's a bug that will be fixed.

**Comment by CoreyDotCom** [comment]
Also make sure you have the latest build that was released yesterday? Perhaps it was fixed recently (the undo portion).

**Comment by nhalbakk** [comment]
This should be resolved in the current Public Preview build.
