### ISSUE TITLE
Switch images-background images

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#9]
We should be able to switch between both image placed and frame with an image inside.

Sometimes, you'll just drag and drop images, sometimes you'll use them as backgrounds, and you might realize (too late) it's the other kind you wanted.

A way to switch via ctrl/right-click, somewhere in the menus, maybe in the style panel.

Of course, switch should keep the most similar view available…

**Comment by jtlafferty** [comment]
This is in progress!

**Comment by jtlafferty** [comment]
This should be available in the next update of Edge Reflow. You will be able to do the following:
1. Right-click on an image to change it into a div with a background image.
2. Right-click on an image to change it into the background image of it's current parent.
