### ISSUE TITLE
Cannot import paragraph styles in psd to Reflow

### ISSUE THREAD

**Issue by vixx** [edge-reflow/issues#92]
I've designed my website layout in Photoshop. I've created paragraph styles and character styles for my typography within Photoshop. It doesn't recognize my paragraph and character styles when I open transfer it to Edge Reflow.

**Comment by vmitnick** [comment]
What sort of paragraph and character style in particular are you losing? I expect that there are some things we do not yet import but we can, others we can't import, and there also may be others that are broken, so your answer can help us to figure out which case this is.

**Comment by vixx** [comment]
I created a paragraph style with these properties:

Font Family: Arial
Font Style: Regular
Size: 80pt

I then turned on generate and exported a reflow project. 
When I open my reflow project, it doesn't register any of my paragraph style properties. The font size is still Arial, but it shows up as a 14 pt. size. 

Hope this is clear.

**Comment by vmitnick** [comment]
I'm on this.

**Comment by vmitnick** [comment]
This seems to be a bug on the photoshop side, where we don't even get this data. I'll file an issue for them.

**Comment by vmitnick** [comment]
The photoshop team is looking at this: http://watsonexp.corp.adobe.com/#bug=3641154

**Comment by vmitnick** [comment]
This was fixed in Photoshop, so now works as expected.
