### ISSUE TITLE
Regions order

### ISSUE THREAD

**Issue by fr32c** [edge-reflow/issues#94]
I expected to work on the regions order all by myself (sing), but when i move frames, they are reordered and i cannot seem to interfere.

Say i have a long text flowed into 4 adjacent regions (4 squares). 

![reflow-4frames](https://f.cloud.github.com/assets/2315207/1207904/fcc20d24-25c3-11e3-93e5-17e716f7345c.png)

If i move one of the frame with the mouse under the 3 frames, the order changes, which is already annoying if i wanted to have some sort of checkerboard flow.

![reflow-4frames-mouse](https://f.cloud.github.com/assets/2315207/1207903/fcbf3892-25c3-11e3-97c6-5d614538d301.png)

Now, if i move the same frame with the keyboard, the order keeps intact.

![reflow-4frames-keyboard](https://f.cloud.github.com/assets/2315207/1207902/fcbbd292-25c3-11e3-8317-3450186c417c.png)

Where it becomes tricky : 
if i then move the frame with the mouse, i get the new (undesired) order.
if i only resize that frame, it's ok, there's no reorder.

**Comment by jtlafferty** [comment]
What you are seeing is the DOM reordering. If you do not want it to reorder, do shift+cmd+drag while moving. Please let me know if that helps.

**Comment by nhalbakk** [comment]
Closing for now.  If you have further info/feedback, please let us know.
